name: Publish Archivar Docker
on: [push]
jobs:
  build-and-publish-head:
    runs-on: [ubuntu-latest]
    if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: archivar
          image-tag: head
          dockerfile: docker/Dockerfile

  build-and-publish-latest:
    runs-on: [ubuntu-latest]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Debug
        run: ls
      - name: Debug
        run: ls docker

      - name: Debug
        run: pwd

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: archivar
          image-tag: latest
          dockerfile: docker/Dockerfile
          build-context: .
