name: Publish New Tag Packages
on:
  push:
    tags:
      - "**"

jobs:
  build-and-publish-release-tags:
    runs-on: [self-hosted]

    steps:
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'

      - name: Use parsed semver
        run: |
          echo "major:       v${{ steps.semver_parser.outputs.major }}"
          echo "minor:       v${{ steps.semver_parser.outputs.minor }}"
          echo "patch:       v${{ steps.semver_parser.outputs.patch }}"
          echo "prerelease:  v${{ steps.semver_parser.outputs.prerelease }}"
          echo "build:       v${{ steps.semver_parser.outputs.build }}"
          echo "fullversion: v${{ steps.semver_parser.outputs.fullversion }}"

      - uses: actions/checkout@v2

      - name: Build and Publish latest Release Patch
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: archivar
          image-tag: ${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
          dockerfile: docker/Dockerfile
          build-context: .

      - name: Build and Publish latest Release Minor
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: archivar
          image-tag: ${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
          dockerfile: docker/Dockerfile
          build-context: .

      - name: Build and Publish latest Release Major
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: archivar
          image-tag: ${{ steps.semver_parser.outputs.major }}
          dockerfile: docker/Dockerfile
          build-context: .
